### ISSUE TITLE
star toggle isn't changing on click

### ISSUE THREAD

**Issue by m-e-h** [helgatheviking/Featured-Item-Metabox#6]
also opening "quick edit" resets to the item to unchecked.

**Comment by helgatheviking** [comment]
Thanks for the report. I will try to check this out as soon as I can.

**Comment by helgatheviking** [comment]
The star seems to toggle fine on click. But I do see the problem that if you click on the star and then click quick edit, the quick edit doesn't update with the new value.

**Comment by m-e-h** [comment]
Just tried again and the toggle star is broken only when "Completely remove options on plugin removal" is selected in the settings.

**Comment by helgatheviking** [comment]
Well that is weird as hell, but did help me find the problem. can you try 1.3.2?

**Comment by m-e-h** [comment]
Yep. The scripts are loading now. Thanks!
